### ISSUE TITLE
能否增加配置网络代理的功能？

### ISSUE THREAD

**Issue by alucadoli** [xisuo67/XHS-Spider#105]
目前需要网络代理上网的话，无法使用

**Comment by xisuo67** [comment]
详细描述一下你说的情况，长期翻墙没遇到你说的这种情况！国外用户似乎也能正常使用

**Comment by alucadoli** [comment]
系统配置见图，上网必须配置系统网络代理。目前App是否会自动读取这个地方设置的代理，然后通过代理访问Internet？
另外，如果支持的话，能否在配置界面增加一个选项，让用户自主选择是否需要使用代理，或者设置自己的代理

![image](https://github.com/xisuo67/XHS-Spider/assets/30334315/bcee44d7-dc1f-492a-a690-3b3f7b76c4c0)

**Comment by xisuo67** [comment]
正常来说，你能正常访问网络，就能使用软件采集数据！你这台电脑能访问小红书网站吗？如果可以，你看一下程序下面日志有没有报错

**Comment by alucadoli** [comment]
我的浏览器通过系统代理能够访问和打开小红书，但是App却报错，下面是日志。
(10.3.246.5:8500) 这个是系统的网络代理参数。

2023-09-13 15:22:57.308 [1] ERROR XHS.Spider.ViewModels.SettingsViewModel
系统参数更新失败
FreeSql: Not updatable, no value for primary key set: (0, 1, C:\Users\cnalli\Documents\小红书, True, False, False, True, , True, True)
   at FreeSql.DbSet`1.Update(TEntity data)
   at FreeSql.BaseRepository`1.Update(TEntity entity)
   at XHS.Spider.ViewModels.SettingsViewModel.UpdateSettingConfig() in G:\GitHub\个人\XHS-Spider-Pro\src\XHS.Spider\ViewModels\SettingsViewModel.cs:line 139


2023-09-13 15:23:05.319 [17] ERROR XHS.Spider.Helpers.UpdateCheckerServer
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10.3.246.5:8500)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at UpdateChecker.Utils.HttpExtensions.GetJsonAsync[T](HttpClient client, String url, CancellationToken token)
   at UpdateChecker.GitHubReleasesUpdateChecker.CheckAsync(HttpClient client, CancellationToken token)
   at UpdateChecker.GitHubReleasesUpdateChecker.CheckAsync(CancellationToken token)
   at XHS.Spider.Helpers.UpdateCheckerServer.Check(Boolean notifyNoFound) in G:\GitHub\个人\XHS-Spider-Pro\src\XHS.Spider\Helpers\UpdateCheckerServer.cs:line 85

**Comment by xisuo67** [comment]
这是一个悲伤的故事，迭代计划中暂时没考虑代理问题！
这个问题后面会考虑纳入迭代计划，只是近期由于工作原因，实在太忙，暂时没办法增加这个功能！

**Comment by CN-make** [comment]
國外也是可以直連小紅書的啊 是不是因為掛載VPN才導致無法正常使用的呢

**Comment by xisuo67** [comment]
> Not updatable, no value fo

这个日志看起来像没有更新本地数据库成功，尝试着在你的运行目录下，找到Spider.db文件后删除，再重新运行一下试试
