### ISSUE TITLE
显示“硬件信息获取失败，无法绑定授权信息”

### ISSUE THREAD

**Issue by yuchen21-web** [xisuo67/XHS-Spider#110]
大佬看看我这，搜了下log日志，发现有这个错误，是不是电脑太老的原因，7、8年前的老电脑了

2023-09-16 11:00:16.138 [5] ERROR XHS.Spider.Views.Windows.MainWindow
硬件信息获取失败
The type initializer for 'SecurityServiceProvider.MachineInfo' threw an exception.
   at SecurityServiceProvider.MachineInfo..ctor() in G:\GitHub\个人\XHS-Spider-Pro\src\SecurityServiceProvider\MachineInfo.cs:line 206
   at XHS.Spider.Views.Windows.MainWindow.VerifyLicensesCode() in G:\GitHub\个人\XHS-Spider-Pro\src\XHS.Spider\Views\Windows\MainWindow.xaml.cs:line 279

**Comment by xisuo67** [comment]
你是什么系统？

**Comment by xisuo67** [comment]
https://dotnet.microsoft.com/zh-cn/download/dotnet-framework   微软官网安装4.8运行时再重新试一下

**Comment by yuchen21-web** [comment]
> https://dotnet.microsoft.com/zh-cn/download/dotnet-framework 微软官网安装4.8运行时再重新试一下

谢谢
