### ISSUE TITLE
尝试多个版本程序均闪退

### ISSUE THREAD

**Issue by BlackGu1tar** [xisuo67/XHS-Spider#32]
安装多个.net 6.0及以上的环境都不行，XHS-Spider从 v1.0.0.6开始直到最新版都这情况，v1.0.0.5菜单正常使用。

报错在事件查看器中如下，和这个路径有关系吗？

```
 at XHS.Spider.Views.Pages.Search.InitializeAsync() in G:\代码\GitHub\WPF项目\XHS-Spider\src\XHS.Spider\Views\Pages\Search.xaml.cs:line 51
```
```shell
错误应用程序名称: XHS.Spider.exe，版本: 1.0.0.8，时间戳: 0x63cf74d2
错误模块名称: KERNELBASE.dll，版本: 10.0.17763.134，时间戳: 0x1659a33b
异常代码: 0xe0434352
错误偏移量: 0x0000000000055299
错误进程 ID: 0xc9c4
错误应用程序启动时间: 0x01d98df18de04b37
错误应用程序路径: C:\Users\Administrator\Downloads\XHS.Spider-v1.0.0.8\XHS.Spider-v1.0.0.8\XHS.Spider.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 56be141c-0f1b-4a3a-a85b-53ca90bdefe0
错误程序包全名: 
错误程序包相对应用程序 ID: 
```

```shell
Application: XHS.Spider.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: 系统找不到指定的文件。 (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass34_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at XHS.Spider.Views.Pages.Search.InitializeAsync() in G:\代码\GitHub\WPF项目\XHS-Spider\src\XHS.Spider\Views\Pages\Search.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at XHS.Spider.App.Main()

```

**Comment by BlackGu1tar** [comment]
应该不是系统问题，虚拟机多个win10版本系统都试了。
.net环境：
dotnet-sdk-6.0.100-win-x64
windowsdesktop-runtime-6.0.0-win-x64
windowsdesktop-runtime-6.0.16-win-x64
dotnet-sdk-6.0.408-win-x64

**Comment by xisuo67** [comment]
你的问题是因为没有webview2的运行时环境，错误提示**Couldn't find a compatible Webview2 Runtime installation to host WebViews.**

可查看链接，解决你的问题[相关问题解决方案](https://github.com/RickStrahl/MarkdownMonster/issues/730)

[webview2运行时下载](https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section)

**Comment by xisuo67** [comment]
如果问题得到解决的话，记得关闭掉这个issuse哦！
@BlackGu1tar

**Comment by BlackGu1tar** [comment]
感谢，已解决！系统把webview精简掉了。

**Comment by df865017** [comment]
同样的报错，问题解决，覆盖安装webview。下载链接：https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section

系统说明：win10 X64 闪退问题

1.如何查日志：
win10 搜索事件查看器，比较慢会卡一下，耐心等待。然后出来最近一条应用程序报错信息，点开。
![image](https://github.com/xisuo67/XHS-Spider/assets/7711900/2ab1dd0a-762e-4c1f-85b5-912da91fbb54)

2.对应报错信息一致，开始重新安装webview吧。
错误应用程序名称: XHS.Spider.exe，版本: 1.0.1.3，时间戳: 0x63cf74d2
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.3086，时间戳: 0xe1ac3f79
异常代码: 0xe0434352
错误偏移量: 0x000000000002cf19
错误进程 ID: 0x20e0
错误应用程序启动时间: 0x01d9a9c9b8a42452
错误应用程序路径: C:\Users\Administrator\Downloads\XHS-Spider-v1.0.1.3\XHS-Spider-v1.0.1.3\XHS.Spider.exe
错误模块路径: C:\windows\System32\KERNELBASE.dll
报告 ID: c9e42873-30d3-4650-a4f1-aa544e6aa5b5
错误程序包全名:


下载链接：https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section

**Comment by RichForever888** [comment]
> 

依然报错

**Comment by xisuo67** [comment]
![5O7BNJIG}62JHP9@YOJF @6_tmb](https://github.com/xisuo67/XHS-Spider/assets/22284363/b9175c9c-5441-439f-9982-9f35008c3bb7)
安装不了的话---强力删除C:\Program Files (x86)\Microsoft文件夹，然后以管理员权限运行安装程序即可！
